### ISSUE TITLE
crystalball has numpy incompatability in 0.2.0

### ISSUE THREAD

**Issue by tmolteno** [caracal-pipeline/cult-cargo#75]
Crash while running the crystalball cab in 0.2.0

Looks like a numpy problem.

```
# INFO:    Build complete: /home/tim/.singularity/quay.io-stimela2-crystalball:cc0.2.0.simg                  
2024-12-12 01:03:39 STIMELA.white_belt.predict-model INFO: (singularity build) exited with code 0 after      
0:01:16                                                                                                      
### running /usr/bin/singularity exec --containall --pwd /home/tim/git/molteno/physics/imaging/meerkat --bind
/home/tim/git/molteno/physics/imaging/meerkat:/home/tim/git/molteno/physics/imaging/meerkat:rw               
/home/tim/.singularity/quay.io-stimela2-crystalball:cc0.2.0.simg crystalball --field 2 --output-column       
MODEL_DATA --sky-model sky_models/J0408-6545_L.txt --num-sources 53 --memory-fraction 0.1                    
ms-orig/mt0_b_j0159.ms                                                                                       
# /usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is 
required for this version of SciPy (detected version 2.0.2                                                   
#   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"                                  
#                                                                                                            
# A module that was compiled using NumPy 1.x cannot be run in                                                
# NumPy 2.0.2 as it may crash. To support both 1.x and 2.x                                                   
# versions of NumPy, modules must be compiled with NumPy 2.0.                                                
# Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.                                        
#                                                                                                            
# If you are a user of the module, the easiest solution will be to                                           
# downgrade to 'numpy<2' or try to upgrade the affected module.                                              
# We expect that some modules will need time to support NumPy 2.                                             
#                                                                                                            
# Traceback (most recent call last):  File "/usr/local/bin/crystalball", line 5, in <module>                 
#     from crystalball.crystalball import predict                                                            
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 8, in <module>           
#     from dask.array import PerformanceWarning                                                              
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/__init__.py", line 56, in <module>              
#     from dask.array import backends, fft, lib, linalg, ma, overlap, random                                 
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/backends.py", line 8, in <module>               
#     from dask.array.core import Array                                                                      
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/core.py", line 32, in <module>                  
#     from dask.array.chunk_types import is_valid_array_chunk, is_valid_chunk_type                           
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/chunk_types.py", line 131, in <module>          
#     import scipy.sparse                                                                                    
#   File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 267, in <module>                    
#     from ._csr import *                                                                                    
#   File "/usr/lib/python3/dist-packages/scipy/sparse/_csr.py", line 10, in <module>                         
#     from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,                                     
# AttributeError: _ARRAY_API not found                                                                       
# Traceback (most recent call last):                  
#   File "/usr/local/bin/crystalball", line 5, in <module>                                                   
#     from crystalball.crystalball import predict     
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 8, in <module>           
#     from dask.array import PerformanceWarning       
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/__init__.py", line 56, in <module>              
#     from dask.array import backends, fft, lib, linalg, ma, overlap, random                                 
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/fft.py", line 11, in <module>                   
#     import scipy.fftpack                                                                                   
#   File "/usr/lib/python3/dist-packages/scipy/fftpack/__init__.py", line 94, in <module>                    
#     from ._basic import *                                                                                  
#   File "/usr/lib/python3/dist-packages/scipy/fftpack/_basic.py", line 8, in <module>                       
#     from scipy.fft import _pocketfft                                                                       
#   File "/usr/lib/python3/dist-packages/scipy/fft/__init__.py", line 90, in <module>                        
#     from ._fftlog import fht, ifht, fhtoffset                                                              
#   File "/usr/lib/python3/dist-packages/scipy/fft/_fftlog.py", line 11, in <module>                         
#     from ..special import loggamma, poch                                                                   
#   File "/usr/lib/python3/dist-packages/scipy/special/__init__.py", line 649, in <module>                   
#     from . import _ufuncs                                                                                  
#   File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs                                                
# ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got  
88 from PyObject                                                                                             
2024-12-12 01:03:40 STIMELA.white_belt.predict-model ERROR: step 'white_belt.predict-model' has failed,      
aborting the recipe                                                                                          
```

Probably belongs upstream.

**Comment by o-smirnov** [comment]
I pushed a new image, can you try again?

**Comment by tmolteno** [comment]
Will do. PS. Have begun looking at crystalball.  It may benefit from pyproject.toml, and improved dependencies

**Comment by tmolteno** [comment]
```
MODEL_DATA --sky-model sky_models/J0408-6545_L.txt --num-sources 53 --memory-fraction 0.1                    
ms-orig/mt0_b_j0159.ms                                                                                       
# Traceback (most recent call last):                                                                         
#   File "/usr/local/bin/crystalball", line 8, in <module>                                                   
#     sys.exit(predict())                                                                                    
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 155, in predict          
#     return _predict(args)                                                                                  
#   File "<decorator-gen-1>", line 2, in _predict                                                            
#   File "/usr/local/lib/python3.10/dist-packages/africanus/util/requirements.py", line 159, in _wrapper     
#     raise MissingPackageException(msg)                                                                     
# africanus.util.requirements.MissingPackageException: _predict requires installation of the following       
packages: ['daskms'].                                                                                        
# cannot import name '_execute_task' from 'dask.core' (/usr/local/lib/python3.10/dist-packages/dask/core.py) 
2024-12-12
```

**Comment by o-smirnov** [comment]
Grrr, this new pip is really broken, isn't it? OK, try now...

**Comment by tmolteno** [comment]
I checked quay.io and new image is there. Deleted .simg, but error persists.

```
/home/tim/.singularity/quay.io-stimela2-crystalball:cc0.2.0.simg crystalball --field 2 --output-column       
MODEL_DATA --sky-model sky_models/J0408-6545_L.txt --num-sources 53 --memory-fraction 0.1                    
ms-orig/mt0_b_j0159.ms                                                                                       
# Traceback (most recent call last):                                                                         
#   File "/usr/local/bin/crystalball", line 8, in <module>                                                   
#     sys.exit(predict())                                                                                    
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 155, in predict          
#     return _predict(args)                                                                                  
#   File "<decorator-gen-1>", line 2, in _predict                                                            
#   File "/usr/local/lib/python3.10/dist-packages/africanus/util/requirements.py", line 159, in _wrapper     
#     raise MissingPackageException(msg)                                                                     
# africanus.util.requirements.MissingPackageException: _predict requires installation of the following       
packages: ['daskms'].                                                                                        
# cannot import name '_execute_task' from 'dask.core' (/usr/local/lib/python3.10/dist-packages/dask/core.py) 
2024-12-12 02:47:31 STIMELA.white_belt.predict-model ERROR: step 'white_belt.predict-model' has failed,      
aborting the recipe                                                                                          
```

**Comment by o-smirnov** [comment]
@tmolteno I think adding

```yml
cabs:
  crystalball:
    image:
      version: cc0.1.3
```

might be a workaround for you in the meantime?

**Comment by tmolteno** [comment]
I think it might be because my pyproject.toml didn't depend on codex-africanus[dask]

This is now fixed in the PR on https://github.com/caracal-pipeline/crystalball/pull/64

**Comment by sjperkins** [comment]
Is the above running with crystallball 0.3.0 or master branch? I wager it's 0.3.0 which is an ancient vintage (2020)

**Comment by o-smirnov** [comment]
The original error in the first post was with an install from master on python3.10. The 0.3.0 release didn't install at all (https://github.com/caracal-pipeline/crystalball/issues/65).

@tmolteno I've pushed a 0.4.1 image now (a.k.a. ``latest``), see if that runs?

**Comment by o-smirnov** [comment]
Meh, I've seen this breakage elsewhere. regions moved that function into a sub-module as of 0.6 (I think). OK I'm out of workarounds now, sorry, @sjperkins needed.

**Comment by o-smirnov** [comment]
Actually I see this is already fixed on crystalball master, we just need a new release. I declare 0.4.1 officially broken. :)

@tmolteno, how's the latest master image acting?

**Comment by o-smirnov** [comment]
@tmolteno I pushed a new master image with @sjperkins's latest fixes. Please try again.

**Comment by tmolteno** [comment]
More errors. This looks like the numpy 2.0 requirement. I have an end-to-end testcase using TART data that works using the pyproject.toml from my branch. 
```
# INFO:    Creating SIF file...                                                                                                            
# INFO:    Build complete: /home/tim/.singularity/quay.io-stimela2-crystalball:cc0.2.0.simg                                                
2024-12-12 17:42:32 STIMELA.white_belt.predict-model INFO: (singularity build) exited with code 0 after 0:01:19                            
### running /usr/bin/singularity exec --containall --pwd /home/tim/git/molteno/physics/imaging/meerkat --bind                              
/home/tim/git/molteno/physics/imaging/meerkat:/home/tim/git/molteno/physics/imaging/meerkat:rw                                             
/home/tim/.singularity/quay.io-stimela2-crystalball:cc0.2.0.simg crystalball --field 2 --output-column MODEL_DATA --sky-model              
sky_models/J0408-6545_L.txt --num-sources 53 --memory-fraction 0.1 ms-orig/mt0_b_j0159.ms                                                  
# /usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of  
SciPy (detected version 2.0.2                                        
#   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"   
#
# A module that was compiled using NumPy 1.x cannot be run in                                                                              
# NumPy 2.0.2 as it may crash. To support both 1.x and 2.x                                                                                 
# versions of NumPy, modules must be compiled with NumPy 2.0.                                                                              
# Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.                                                                      
#                                                                                                                                          
# If you are a user of the module, the easiest solution will be to                                                                         
# downgrade to 'numpy<2' or try to upgrade the affected module.                                                                            
# We expect that some modules will need time to support NumPy 2.                                                                           
#                                                                                                                                          
# Traceback (most recent call last):  File "/usr/local/bin/crystalball", line 5, in <module>                                               
#     from crystalball.crystalball import predict                                                                                          
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 8, in <module>                                         
#     from dask.array import PerformanceWarning                                                                                            
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/__init__.py", line 56, in <module>                                            
#     from dask.array import backends, fft, lib, linalg, ma, overlap, random                                                               
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/backends.py", line 8, in <module>                                             
#     from dask.array.core import Array                                                                                                    
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/core.py", line 32, in <module>                                                
#     from dask.array.chunk_types import is_valid_array_chunk, is_valid_chunk_type                                                         
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/chunk_types.py", line 131, in <module>                                        
#     import scipy.sparse                                            
#   File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 267, in <module>                                                  
#     from ._csr import *         
#   File "/usr/lib/python3/dist-packages/scipy/sparse/_csr.py", line 10, in <module>                                                       
#     from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,                                                                   
# AttributeError: _ARRAY_API not found                               
# Traceback (most recent call last):                                 
#   File "/usr/local/bin/crystalball", line 5, in <module>           
#     from crystalball.crystalball import predict                    
#   File "/usr/local/lib/python3.10/dist-packages/crystalball/crystalball.py", line 8, in <module>                                         
#     from dask.array import PerformanceWarning                      
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/__init__.py", line 56, in <module>                                            
#     from dask.array import backends, fft, lib, linalg, ma, overlap, random                                                               
#   File "/usr/local/lib/python3.10/dist-packages/dask/array/fft.py", line 11, in <module>                                                 
#     import scipy.fftpack        
#   File "/usr/lib/python3/dist-packages/scipy/fftpack/__init__.py", line 94, in <module>                                                  
#     from ._basic import *       
#   File "/usr/lib/python3/dist-packages/scipy/fftpack/_basic.py", line 8, in <module>                                                     
#     from scipy.fft import _pocketfft                               
#   File "/usr/lib/python3/dist-packages/scipy/fft/__init__.py", line 90, in <module>                                                      
#     from ._fftlog import fht, ifht, fhtoffset                      
#   File "/usr/lib/python3/dist-packages/scipy/fft/_fftlog.py", line 11, in <module>                                                       
#     from ..special import loggamma, poch                           
#   File "/usr/lib/python3/dist-packages/scipy/special/__init__.py", line 649, in <module>                                                 
#     from . import _ufuncs       
#   File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs        
# ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject               
2024-12-12 17:42:33 STIMELA.white_belt.predict-model ERROR: step 'white_belt.predict-model' has failed, aborting the recipe                
```

**Comment by tmolteno** [comment]
The end-to-end test (including measurement set) is in

https://github.com/tmolteno/crystalball/tree/master/test_data

**Comment by o-smirnov** [comment]
> More errors. This looks like the numpy 2.0 requirement. I have an end-to-end testcase using TART data that works using the pyproject.toml from my branch.
> 

It's like playing whack-a-mole... tests may run in your environment, but a pip install inside a clean image results in breakage. OK, I've added ``pip install - U scipy`` to the image and pushed, try again.

@sjperkins we may need to add an explicit "scipy higher than" requirement. The current install pulls in numpy>=2 but leaves scipy at some older incompatible version.

**Comment by sjperkins** [comment]
Why are we installing scipy at all? A fresh install of 0.4.2 in a virtualenv doesn't show scipy in `pip freeze`.

Could it be that scipy is baked into the image somehow?

**Comment by o-smirnov** [comment]
Good question -- it might be pre-installed in the base image. Let me check.

Looks like dask imports scipy if available:  https://github.com/dask/dask/blob/main/dask/array/chunk_types.py

**Comment by tmolteno** [comment]
Sounds like the package will need a venv to operate? Can we use a default cult_cargo venv for each cab? This might keep the system from polluting the python namespace?

**Comment by sjperkins** [comment]
As a rule I think all of our applications should be installed in venvs

**Comment by o-smirnov** [comment]
It's a good guideline to impose to keep users out of our hair, but seems like a regression if i can't operate outside a venv at all!

**Comment by sjperkins** [comment]
> It's a good guideline to impose to keep users out of our hair, but seems like a regression if i can't operate outside a venv at all!

Perhaps, but isolation as provided by containers, snaps, flatpaks and python virtual environments is designed to circumvent these dependency issues.

**Comment by o-smirnov** [comment]
Which is exactly why I'm trying to come up with a clean Dockerfile. Venv inside container seems like adding another layer of complexity to the process which can bite us down the road.

**Comment by sjperkins** [comment]
I suspect what happened in this case is that a system scipy was installed, built against an older version of numpy. When numpy > 2, was installed any call to scipy was going to break because the system numpy had been replaced. A virtualenv would prevent this.

**Comment by o-smirnov** [comment]
Finally! @tmolteno I believe I have pushed working images. At least your test runs. Lessons learned:

* Dask is sneaky! It will attempt to import scipy and cause kak if it gets hold of a system scipy that clashes with a newly-installed numpy. Since scipy is not in any dependencies in this case, there's nothing pip can do to avoid this. (Solved by stripping scipy out of the base image.)

* Something similar going on with matplotlib, solved by an explicit "pip install -U matplotlib". I'm still investigating why matplotlib is installed to begin with, since it's not a dependency and not in the base image.

**Comment by sjperkins** [comment]
> I'm still investigating why matplotlib is installed to begin with, since it's not a dependency and not in the base image.

Possibly the kernsuite base:

https://github.com/caracal-pipeline/cult-cargo/blob/0aa0fe574dc57514d32c2acf5e423f325170461a/cultcargo/images/base-cult/Dockerfile#L1-L5

**Comment by o-smirnov** [comment]
Yep probably. Basing off kern seemed like a good idea at the time...

**Comment by sjperkins** [comment]
> Yep probably. Basing off kern seemed like a good idea at the time... 

I suspect most of the dask based apps could run off ubuntu-24.04. Could multiple base images be supported?

**Comment by o-smirnov** [comment]
> Could multiple base images be supported?

Absolutely. The builder script will look for a per-package Dockerfile under ``cultcargo/images/package``. Most of these just happen to symlink to https://github.com/caracal-pipeline/cult-cargo/blob/master/cultcargo/images/Dockerfile.generic.pip, which is meant to be a generic Dockerfile for pip installable packages. If something less than generic is required, we put a specific Dockerfile in rather.

**Comment by tmolteno** [comment]
@o-smirnov @sjperkins New images are now working. Why not base the python images of the standard docker python image. (https://hub.docker.com/_/python)?

**Comment by sjperkins** [comment]
> @o-smirnov @sjperkins New images are now working. Why not base the pip installable software images off the standard docker python image. (https://hub.docker.com/_/python)?

There are also the slim containers

https://hub.docker.com/layers/library/python/3.10-slim/images/sha256-0d15918ecae76250659ae3036ad1fc898f801f6cb803860bdf0cc4b27fe316dc

**Comment by sjperkins** [comment]
[This](https://www.kdnuggets.com/how-to-create-minimal-docker-images-for-python-applications)  suggests that the space savings for a slim variant  can be as much as 146MB vs 1.02GB for the full version.

**Comment by tmolteno** [comment]
Issue #77 seems related to this one... tricolour is crashing due to a scipy incompatibility.

**Comment by o-smirnov** [comment]
OK, I pushed new images for crystalball and tricolour based off the standard "slim" containers. At least invoking the command seems to work -- @tmolteno would you please test further?

Slim is not so slim anymore once pip and git is installed, but it did reduce the crystalball image by almost 50%. Only 10% simming for tricolour though.
