### ISSUE TITLE
tricolour cab crashes in 0.2.0

### ISSUE THREAD

**Issue by tmolteno** [caracal-pipeline/cult-cargo#77]
The tricolour cab seems to have issues similar to crystalball:

This is running under python3.8. I get the following
```
### running /usr/bin/singularity exec --containall --pwd                                    
/home/tim/git/molteno/physics/imaging/meerkat --bind                                        
/home/tim/git/molteno/physics/imaging/meerkat:/home/tim/git/molteno/physics/imaging/meerkat:
rw --bind /home/tim/tmp:/home/tim/tmp:ro                                                    
/home/tim/.singularity/quay.io-stimela2-tricolour:cc0.2.0.simg tricolour --config           
tricolour/initial-strategy.yml --flagging-strategy standard --data-column DATA --field-names
2 --disable-post-mortem --temporary-directory /home/tim/tmp --subtract-model-column         
MODEL_DATA ms-orig/mt0_b_j0159.ms             
# Traceback (most recent call last):                                                        
#   File "/usr/local/bin/tricolour", line 5, in <module>                                    
#     from tricolour.apps.tricolour.app import main                                         
#   File "/usr/local/lib/python3.8/dist-packages/tricolour/apps/tricolour/app.py", line 29, 
in <module>                                                                                 
#     from tricolour.mask import collect_masks, load_mask                                   
#   File "/usr/local/lib/python3.8/dist-packages/tricolour/mask.py", line 10, in <module>   
#     from scipy.ndimage import binary_dilation                                             
#   File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 153, in <module>          
#     from scipy._lib._ccallback import LowLevelCallable                                    
#   File "/usr/lib/python3/dist-packages/scipy/_lib/_ccallback.py", line 1, in <module>     
#     from . import _ccallback_c              
# ImportError: cannot import name '_ccallback_c' from 'scipy._lib'                          
(/usr/lib/python3/dist-packages/scipy/_lib/__init__.py)                                     
2024-12-13 04:40:28 STIMELA.white_belt.fluxcal-flag ERROR: step 'white_belt.fluxcal-flag'   
has failed, aborting the recipe               
```

Looks like incompatibility between a system installed scipy. The tricolour package may need to move to pyproject.toml and also be installed in a virtualenv?

**Comment by o-smirnov** [comment]
Yep, same story. Except scipy is an explicit dependency this time, so this is a pip fail. I'll push an updated image shortly.

**Comment by o-smirnov** [comment]
OK try now?

**Comment by tmolteno** [comment]
Still failing. I'm having a go at bringing tricolour up to date. Will also add an end-to-end test.
```
# tricolour - 2024-12-13 21:31:38,147 INFO - Flagging per correlation ('standard' mode)     
# RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd . 
Check the section C-API incompatibility at the Troubleshooting ImportError section at       
https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for   
indications on how to solve this problem .                                                  
# Traceback (most recent call last):                                                        
#   File "/usr/local/lib/python3.8/site-packages/daskms/table_proxy.py", line 159, in       
__call__                                                                                    
#     return _table_cache\[key]                                                             #   File "/usr/local/lib/python3.8/weakref.py", line 131, in __getitem__                    
```

**Comment by o-smirnov** [comment]
How's it looking now? The latest 0.2.0 image runs for me (or at least displays help).
